feat: Update the community PR message to have collapsible sections
openedx/openedx-webhooks pull request #328
Opened 2024-12-30 11:28 UTC by xitij2000

The current community message is quite long and key information is hard to access at a glance. This condenses the message by collapsing sections that have verbose information and putting key information at the start of the message.

2024-12-30 11:28 UTC, openedx-webhooks commented
Thanks for the pull request, @xitij2000!

### What's next?

*Please work through the following steps to get your changes ready for engineering review:*

#### :radio_button: Get product approval

If you haven't already, [check this list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Does-my-contribution-require-Product-Review%3F) to see if your contribution needs to go through the product review process.

- If it does, you'll need to submit a product proposal for your contribution, and have it reviewed by the [Product Working Group](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3449028609/Product+Working+Group).
    - This process (including the steps you'll need to take) is documented [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Product-Review-Process).
- If it doesn't, simply proceed with the next step.

#### :radio_button: Provide context

To help your reviewers and other members of the community understand the purpose and larger context of your changes, feel free to add as much of the following information to the PR description as you can:

- Dependencies
  > This PR must be merged before / after / at the same time as ...
- Blockers
  > This PR is waiting for OEP-1234 to be accepted.
- Timeline information
  > This PR must be merged by XX date **because** ...
- Partner information
  > This is for a course on edx.org.
- Supporting documentation
- Relevant [Open edX discussion forum](https://discuss.openedx.org/) threads





#### :radio_button: Get a green build

If one or more checks are failing, continue working on your changes until this is no longer the case and your build turns green.


#### :radio_button: Update the status of your PR

Your PR is currently marked as a draft.  After completing the steps above, update its status by clicking "Ready for Review", or removing "WIP" from the title, as appropriate.

<!-- comment:end_of_wip -->


#### :radio_button: Let us know that your PR is ready for review:

### Who will review my changes?


This repository is currently maintained by `@feanil`.  Tag them in a comment and let them know that your changes are ready for review.


### Where can I find more information?

If you'd like to get more details on all aspects of the review process for open source pull requests (OSPRs), check out the following resources:

- [Overview of Review Process for Community Contributions](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/FAQ-about-pull-requests.html)
- [Pull Request Status Guide](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/pull-request-statuses.html)
- [Making changes to your pull request](https://docs.openedx.org/en/latest/documentors/how-tos/make_changes_to_your_pull_request.html)

### When can I expect my changes to be merged?

Our goal is to get community contributions seen and reviewed as efficiently as possible.

However, the amount of time that it takes to review and merge a PR can vary significantly based on factors such as:

- The size and impact of the changes that it introduces
- The need for product review
- Maintenance status of the parent repository

:bulb: *As a result it may take up to several weeks or months to complete a review and merge your PR.*

<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IHRydWV9 -->

2025-01-06 19:08 UTC, feanil approved these changes
Looks good, I'll deploy it.

2025-01-06 19:23 UTC, feanil requested changes

2025-01-06 19:23 UTC, feanil commented on openedx_webhooks/templates/github_community_pr_comment.md.j2
> +<details><summary>#### :radio_button: Find a technical reviewer</summary>
Once you start using the HTML detail element, the markdown `#` is no longer respected. You should used `<h4>` instead.  See an example of how this plays out in https://github.com/openedx/webhook-test-repo/pull/18

2025-01-07 09:33 UTC, xitij2000 commented on openedx_webhooks/templates/github_community_pr_comment.md.j2
> +<details><summary>#### :radio_button: Find a technical reviewer</summary>
I've applied your suggestion. Thanks!

2025-01-07 17:49 UTC, feanil reviewed
Found a couple more issues.

2025-01-07 17:49 UTC, feanil commented on openedx_webhooks/templates/github_community_pr_comment.md.j2
> +<summary>### Where can I find more information?<summary>
```suggestion
<summary><h3>Where can I find more information? </h3></summary>
```

2025-01-07 17:49 UTC, feanil commented on openedx_webhooks/templates/github_community_pr_comment.md.j2
> +<summary>### When can I expect my changes to be merged?</summary>
```suggestion
<summary><h3>When can I expect my changes to be merged?</h3></summary>
```

2025-01-13 17:26 UTC, feanil commented
I squashed and merged this via https://github.com/openedx/openedx-webhooks/pull/332 since I couldn't edit this PR in-place.

2025-01-13 17:26 UTC, closed without merging

2025-01-14 07:51 UTC, itsjeyd approved these changes
@xitij2000 Thanks for these changes! They LGTM. Just one comment about rewording the section on finding a technical reviewer slightly, :+1: once that's addressed.

2025-01-14 07:51 UTC, itsjeyd commented on openedx_webhooks/templates/github_community_pr_comment.md.j2
> +2. Find their GitHub handle [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3548807177/Community+Contributions+Project+Manager#Current-OSPR-Project-Managers).
@xitij2000 Maybe we could reword this slightly to better connect it to the instruction below that always gets displayed ("Once you've gone through the following steps ...") and remove duplicate content:

```markdown
To get help with finding a technical reviewer, reach out to the community contributions project manager for this PR:

1. On the right-hand side of the PR, find the Contributions project, click the caret in the top right corner to expand it, and check the "Primary PM" field for the name of your project manager.
2. Find their GitHub handle [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3548807177/Community+Contributions+Project+Manager#Current-OSPR-Project-Managers).
```

This way there's less potential for confusion about when to let the maintainer(s)/PM know that a PR is ready for review.